### ISSUE TITLE
Arguments scope bug

### ISSUE THREAD

**Issue by numbcoder** [BYVoid/continuation#22]
js code:
```js
var read = function() {
  var content = 'abc';
  fs.readFile('a.txt', 'utf-8', cont(err, content));
};
```
will be compiled to
```js
var read;
read = function () {
  var content, err;
  content = 'abc';
  fs.readFile('a.txt', 'utf-8', function (arguments, _$param1, _$param2) {
    err = _$param1;
    content = _$param2;
  }.bind(this, arguments));
};
```
the variable `content` is changed.

So, the correct compiled result is that:
```js
var read;
read = function () {
  var content;
  content = 'abc';
  fs.readFile('a.txt', 'utf-8', function (arguments, _$param1, _$param2) {
    var content, err;
    err = _$param1;
    content = _$param2;
  }.bind(this, arguments));
};
```

What do you think about it?

**Comment by shankerwangmiao** [comment]
I do not think it is a bug. What if `content` is from outer scope? Using "cont()", there is no concept of callback functions, so there is no need to limit such a variable into the "callback function" compiled into.

**Comment by BYVoid** [comment]
This is an expected behavior. `cont` or `obtain` doesn't create a scope.
